// Auto-generated by tools/sync_photos.py -- do not edit by hand, it gets
// overwritten on every sync run. Starts empty until the sync script has run
// at least once against the real server.
window.PHOTO_MANIFEST = [];
