// Streamer roster -- built from the application spreadsheet responses.
// Each entry credits whichever of Twitch/YouTube/Kick they listed, in that
// priority order, using their own given handle. Entries with no usable
// Twitch/YouTube/Kick handle (jokes, unrelated platforms, unreadable
// answers) were left out rather than guessed at.
var STREAMER_ROSTER = [
  { name: 'andoucondo', platform: 'Twitch', url: 'https://www.twitch.tv/andoucondo', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Icklyre', platform: 'Twitch', url: 'https://www.twitch.tv/Icklyre', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Foxblank', platform: 'Twitch', url: 'https://www.twitch.tv/Foxblank', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'punchyyume', platform: 'Twitch', url: 'https://www.twitch.tv/punchyyume', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Sterbenbruh', platform: 'YouTube', url: 'https://www.youtube.com/@Sterbenbruh', icon: 'img/icons/youtube_icon.png' },
  { name: 'ockalive', platform: 'Twitch', url: 'https://www.twitch.tv/ockalive', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'alia_you_ali_40', platform: 'Twitch', url: 'https://www.twitch.tv/alia_you_ali_40', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'BaitrOrange', platform: 'Twitch', url: 'https://www.twitch.tv/BaitrOrange', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'FD_shadows', platform: 'Twitch', url: 'https://www.twitch.tv/FD_shadows', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'KageUmbra', platform: 'YouTube', url: 'https://www.youtube.com/@KageUmbra', icon: 'img/icons/youtube_icon.png' },
  { name: 'dontblinkdocwho3095', platform: 'YouTube', url: 'https://www.youtube.com/@dontblinkdocwho3095', icon: 'img/icons/youtube_icon.png' },
  { name: 'lethalbeannn', platform: 'Twitch', url: 'https://www.twitch.tv/lethalbeannn', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'SwishaFlame', platform: 'Twitch', url: 'https://www.twitch.tv/SwishaFlame', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'dasduhh', platform: 'Twitch', url: 'https://www.twitch.tv/dasduhh', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'the_beany_boi', platform: 'Twitch', url: 'https://www.twitch.tv/the_beany_boi', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'm0rals', platform: 'Twitch', url: 'https://www.twitch.tv/m0rals', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'DylanzFr', platform: 'Twitch', url: 'https://www.twitch.tv/DylanzFr', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Ocramham', platform: 'Twitch', url: 'https://www.twitch.tv/Ocramham', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'bbl_izzy', platform: 'Twitch', url: 'https://www.twitch.tv/bbl_izzy', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Levsees', platform: 'Twitch', url: 'https://www.twitch.tv/Levsees', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'starleiaa', platform: 'Twitch', url: 'https://www.twitch.tv/starleiaa', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'LemonXPotatoes', platform: 'Twitch', url: 'https://www.twitch.tv/LemonXPotatoes', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'fakememe69', platform: 'Twitch', url: 'https://www.twitch.tv/fakememe69', icon: 'img/icons/twitch_icon_bg.png' },
  { name: '18danner18', platform: 'Twitch', url: 'https://www.twitch.tv/18danner18', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Imissbari', platform: 'Twitch', url: 'https://www.twitch.tv/Imissbari', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'bigbosspauli', platform: 'Twitch', url: 'https://www.twitch.tv/bigbosspauli', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Conorsanime', platform: 'Twitch', url: 'https://www.twitch.tv/Conorsanime', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Riptide_pod', platform: 'Twitch', url: 'https://www.twitch.tv/Riptide_pod', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'IITZHENRYY', platform: 'Twitch', url: 'https://www.twitch.tv/IITZHENRYY', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'vj', platform: 'Twitch', url: 'https://www.twitch.tv/vj', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'ryanhellawavy', platform: 'Twitch', url: 'https://www.twitch.tv/ryanhellawavy', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'korishimasu', platform: 'Twitch', url: 'https://www.twitch.tv/korishimasu', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'WeenieHQ', platform: 'Twitch', url: 'https://www.twitch.tv/WeenieHQ', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'insxide', platform: 'Twitch', url: 'https://www.twitch.tv/insxide', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'pohaho', platform: 'Twitch', url: 'https://www.twitch.tv/pohaho', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'FoxyNova626', platform: 'Twitch', url: 'https://www.twitch.tv/FoxyNova626', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Lazy_Cappy', platform: 'Twitch', url: 'https://www.twitch.tv/Lazy_Cappy', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'ilyJesus_', platform: 'Twitch', url: 'https://www.twitch.tv/ilyJesus_', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'lynxisalright', platform: 'Twitch', url: 'https://www.twitch.tv/lynxisalright', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'the_tamachi', platform: 'Twitch', url: 'https://www.twitch.tv/the_tamachi', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'morsecde_', platform: 'Twitch', url: 'https://www.twitch.tv/morsecde_', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'JoshxVue', platform: 'Twitch', url: 'https://www.twitch.tv/JoshxVue', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'ToxiccScope', platform: 'Twitch', url: 'https://www.twitch.tv/ToxiccScope', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Kaito', platform: 'Twitch', url: 'https://www.twitch.tv/Kaito', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Mars_ultor001', platform: 'Twitch', url: 'https://www.twitch.tv/Mars_ultor001', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Ezrasinsanity', platform: 'Twitch', url: 'https://www.twitch.tv/Ezrasinsanity', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Touta2x', platform: 'Twitch', url: 'https://www.twitch.tv/Touta2x', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'SoaraJPG', platform: 'Twitch', url: 'https://www.twitch.tv/SoaraJPG', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'viskipoint', platform: 'Twitch', url: 'https://www.twitch.tv/viskipoint', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Goomay', platform: 'Twitch', url: 'https://www.twitch.tv/Goomay', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'shaliin_', platform: 'Twitch', url: 'https://www.twitch.tv/shaliin_', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'RoninSherry', platform: 'Twitch', url: 'https://www.twitch.tv/RoninSherry', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'BombDiggy', platform: 'Twitch', url: 'https://www.twitch.tv/BombDiggy', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'ZerittYT', platform: 'YouTube', url: 'https://www.youtube.com/@ZerittYT', icon: 'img/icons/youtube_icon.png' },
  { name: 'TevWitaBev', platform: 'Twitch', url: 'https://www.twitch.tv/TevWitaBev', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Dots420', platform: 'Twitch', url: 'https://www.twitch.tv/Dots420', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'Goomgy', platform: 'Twitch', url: 'https://www.twitch.tv/Goomgy', icon: 'img/icons/twitch_icon_bg.png' },
  { name: 'KATBITES', platform: 'Twitch', url: 'https://www.twitch.tv/KATBITES', icon: 'img/icons/twitch_icon_bg.png' },
];